In [1]:
import numpy as np

In [2]:
arr = np.arange(2,10)

In [3]:
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# basic index like lists indxing

In [5]:
arr[:4] = 100
arr

array([100, 100, 100, 100,   6,   7,   8,   9])

In [6]:
arr = np.arange(2,10)
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[:] # everything

array([2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
slice  = arr[:5]


In [9]:
slice


array([2, 3, 4, 5, 6])

In [10]:
slice  = arr[:5]
slice

array([2, 3, 4, 5, 6])

In [11]:
# recalling the original array
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
copy = arr.copy()
arr
copy

array([2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
copy[:] = 100
copy
# changing the copied array doesnot effect the original array

array([100, 100, 100, 100, 100, 100, 100, 100])

In [15]:
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# INDEXING A 2-D ARRAY
ar = np.array([[1,20,55],[54,21,89],[98,36,26]])
ar

array([[ 1, 20, 55],
       [54, 21, 89],
       [98, 36, 26]])

In [17]:
ar[1][0]


54

In [18]:
# alternative method
ar[1,0]

54

In [23]:
ar[:2,1:]


array([[20, 55],
       [21, 89]])

In [20]:
a = np.array([[1,20,55],[54,21,89],[98,36,26]])
a

array([[ 1, 20, 55],
       [54, 21, 89],
       [98, 36, 26]])

In [22]:
a[:2,1:]


array([[20, 55],
       [21, 89]])

In [25]:
b = np.arange(1,15)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
b > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [27]:
aka = b > 5


In [28]:
aka

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [30]:
b[aka]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
# only true values provided

In [32]:
b[b>4]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
w = np.arange(50).reshape(5,10)
w

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [34]:
w[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [35]:
w[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])