In [2]:
import numpy as np

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
# a.reshape(5)

ValueError: cannot reshape array of size 10 into shape (5,)

In [14]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [15]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [17]:
l = [[0,1,2],[3,4,5],[6,7,8]]
np.array(l)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.random.randn(1,1)

array([[0.96538331]])

In [28]:
np.random.rand(25)

array([0.14299109, 0.56024128, 0.96117681, 0.39432439, 0.58338971,
       0.22253724, 0.07455914, 0.99641848, 0.77918664, 0.28683794,
       0.39073367, 0.9577225 , 0.62196145, 0.70291286, 0.36614462,
       0.34904663, 0.4461921 , 0.30172928, 0.10325338, 0.9095548 ,
       0.20102218, 0.10514897, 0.9978388 , 0.0386671 , 0.86843879])

In [32]:
# np.random.randint(10,10,2)

ValueError: low >= high

In [33]:
# np.random.randn(0,1)

array([], shape=(0, 1), dtype=float64)