In [1]:
import numpy as np


In [2]:
li = [1,2,3]

In [3]:
arr = np.array(li)
arr

array([1, 2, 3])

In [4]:
# 2-D arrays
li_1 = [[1,2,3],[4,5,6],[7,8,9]]
np.array(li_1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# range
# index logic
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
# for 0's arr
np.zeros(4)

array([0., 0., 0., 0.])

In [8]:
np.zeros((4,4)) # in tuple ((row,col))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
# for certain equal-spaced "ONE-DIMENSIONAL" array
np.linspace(2,10,20) # (start,stop,no. of arrays)

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

In [16]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
# for random no. 1D    " EQUALLY - DISTRIBUTED"
np.random.rand(4)
# 2D
np.random.rand(5,5) # (row,col)

array([[0.06567448, 0.01927479, 0.19592945, 0.76566503, 0.54031921],
       [0.51765597, 0.30273053, 0.58338198, 0.82999897, 0.7599431 ],
       [0.13387566, 0.66493774, 0.86420035, 0.14086779, 0.54388481],
       [0.56048812, 0.15515111, 0.31192757, 0.94963395, 0.22135612],
       [0.0846058 , 0.09947214, 0.59029231, 0.69206818, 0.80636526]])

In [18]:
np.random.randn(4,4)
# unequally dist.

array([[ 1.09652526,  0.97803061, -0.76425143, -1.57794921],
       [-0.19012262, -0.56832238, -1.43071255,  1.19470261],
       [ 1.23958087,  0.9396554 ,  0.55539187,  1.18998494],
       [ 1.48877831,  0.03458566,  0.4882715 , -0.28116433]])

In [19]:
np.random.randint(2,100,8) # (start , end , quantity)

array([15, 80, 88, 26, 27,  2, 28,  4])

In [22]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
np.random.randint(0,20,6)

array([ 5, 19, 16,  6, 19,  4])

In [24]:
a.reshape(4,5) # no. of elements in array 4*5=20

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
r = np.random.randint(0,20,10)
r

array([15, 17,  3,  6,  5, 10,  4, 13,  7,  2])

In [30]:
r.max()

17

In [31]:
r.min()

2

In [32]:
# index locaton of max val.
r.argmax()

1

In [33]:
r.argmin()

9

In [40]:
w1 = np.arange(10)
w1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr.shape

(3,)

In [46]:
z=arr.reshape(2,2)
z

ValueError: cannot reshape array of size 3 into shape (2,2)

In [47]:
arr.dtype

dtype('int64')